version: 2

sources:
  - name: results
    database: "{{ env_var('DBT_DATABASE', 'test') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'dbt_fal') }}"
    tables:
      - name: "ns__{{ env_var('DB_NAMESPACE', '') }}__ns__some_source"

models:
  - name: execute_sql_model_one
    meta:
      fal:
        scripts:
          after:
            - fal_scripts/query_other_model.py
            - fal_scripts/run_macro.py
  - name: execute_sql_model_two
