version: 2

models:
  - name: some_model
    meta:
      fal:
        scripts:
          before:
            - fal_scripts/before.py
          after:
            - fal_scripts/after.py

fal:
  scripts:
    before:
      - fal_scripts/before.py
      - fal_scripts/before_b.py
    after:
      - fal_scripts/after.py
