config:
  send_anonymous_usage_stats: False

fal_test:
  target: staging
  outputs:
    staging:
      type: fal
      db_profile: db
    prod:
      type: fal
      db_profile: db
      host: "{{ env_var('FAL_HOST') }}"
      key_secret: "{{ env_var('FAL_KEY_SECRET') }}"
      key_id: "{{ env_var('FAL_KEY_ID') }}"
    db:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('KEYFILE_DIR') }}/keyfile.json"
      project: "{{ env_var('GCLOUD_PROJECT') }}"
      dataset: "{{ env_var('BQ_DATASET') }}"
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
