# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Global hooks (these can be configured with global pyproject.toml)
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: |
          (?x)(
            ^projects/fal_serverless/openapi-fal-rest/
          )
  - repo: https://github.com/hakancelikdev/unimport
    rev: 0.12.1
    hooks:
      - id: unimport
        args:
          - --ignore-init
          - -r
        exclude: |
          (?x)(
            ^projects/fal_serverless/openapi-fal-rest/
          )
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: |
          (?x)(
            ^projects/fal_serverless/openapi-fal-rest/
          )
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
        exclude: |
          (?x)(
            ^projects/fal_serverless/openapi-fal-rest/
          )

  # Monorepo Hooks (e.g. they need to be project specific)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --no-warn-no-return
          - --check-untyped-defs
        additional_dependencies:
          - types-protobuf
          - types-requests
          - types-redis
          - types-pyyaml
        exclude: |
          (?x)(
            test_.*\.py$|
            ^projects/fal_serverless/openapi-fal-rest/
          )
