version: 2

sources:
  - name: results
    database: "{{ env_var('DBT_DATABASE', 'test') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'dbt_fal') }}"
    tables:
      - name: "ns__{{ env_var('DB_NAMESPACE', '') }}__ns__some_source"

models:
  - name: zendesk_ticket_data
    description: zendesk ticket data
    config:
      materialized: table
    meta:
      fal:
        pre-hook:
          - fal_scripts/pre_hook.py
        post-hook:
          - fal_scripts/post_hook.py
          - fal_scripts/post_hook2.py

  - name: agent_wait_time
    description: Agent wait time series
    config:
      materialized: table
    columns:
      - name: y
        tests:
          - not_null
      - name: ds
        tests:
          - not_null
      - name: a
        tests:
          - unique
    meta:
      fal:
        scripts:
          before:
            - fal_scripts/before.py
          after:
            - fal_scripts/after.py

  - name: some_model
    meta:
      fal:
        post-hook:
          - fal_scripts/write_to_model.py

  - name: some_other_model
    meta:
      fal:
        post-hook:
          - fal_scripts/write_to_source.py
