version: 2

sources:
  - name: results
    database: "{{ env_var('DBT_DATABASE', 'test') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'dbt_fal') }}"
    tables:
      - name: some_source
  - name: freshness_test
    database: "{{ env_var('DBT_DATABASE', 'test') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'dbt_fal') }}"
    freshness:
      warn_after: { "count": 5, "period": minute }
      error_after: { "count": 30, "period": minute }
    tables:
      - name: freshness_table
        loaded_at_field: cast(loaded_at as timestamptz)
        columns:
          - name: info
            tests:
              - unique

      - name: freshness_other # does not exist (run time error)
        loaded_at_field: cast(loaded_at as timestamptz)

models:
  - name: zendesk_ticket_data
    description: zendesk ticket data
    config:
      materialized: table
    meta:
      fal:
        post-hook:
          - fal_scripts/post_hook.py
          - fal_scripts/post_hook2.py

  - name: agent_wait_time
    description: Agent wait time series
    config:
      materialized: table
    columns:
      - name: y
        tests:
          - not_null
      - name: ds
        tests:
          - not_null
      - name: a
        tests:
          - unique
    meta:
      fal:
        scripts:
          before:
            - fal_scripts/before.py
          after:
            - fal_scripts/after.py

  - name: some_model
    meta:
      fal:
        post-hook:
          - fal_scripts/write_to_model.py

  - name: some_other_model
    meta:
      fal:
        post-hook:
          - fal_scripts/write_to_source.py

fal:
  scripts:
    - fal_scripts/freshness.py
