version: 2

models:
  - name: zendesk_ticket_data
    meta:
      fal:
        scripts:
          after:
            - fal_scripts/check_extra.py

  - name: empty_model

  - name: empty_model_2
    meta:
      fal:
        scripts:
          before:
            - fal_scripts/before_2.py
          after:
            - fal_scripts/after_2.py

  - name: agent_wait_time
    description: Agent wait time series
    config:
      materialized: table
      tags: daily
    columns:
      - name: y
        tests:
          - not_null
      - name: ds
        tests:
          - not_null
      - name: a
        tests:
          - unique
    meta:
      fal:
        scripts:
          before:
            - fal_scripts/before.py
          after:
            - fal_scripts/after.py
