name: "test"
version: "1.0.0"
config-version: 2
profile: "fal_test"
source-paths: ["models"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "{{ env_var('temp_dir') }}/target"
vars:
  fal-scripts-path: "scripts"
  fal-models-paths: ["fal_models"]

# NOTE: necessary for snowflake projects
# dbt uses adapter_class.Relation, and that is BaseRelation
quoting:
  database: false
  schema: false
  identifier: false

models:
  +schema: custom
