config:
  send_anonymous_usage_stats: False

fal_test:
  target: integration_tests
  outputs:
    dev:
      type: redshift
      host: localhost
      port: 5432
      user: pguser
      password: pass
      dbname: test
      schema: dbt_fal
      threads: 4
    integration_tests:
      type: redshift
      host: "{{ env_var('RS_HOST') }}"
      port: 5432
      user: "{{ env_var('RS_USER') }}"
      password: "{{ env_var('RS_PASSWORD') }}"
      dbname: "{{ env_var('RS_DB_NAME') }}"
      schema: "{{ env_var('RS_SCHEMA') }}"
      threads: 4
