version: 2

sources:
  - name: freshness_test
    database: "{{ env_var('DBT_DATABASE', 'test') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'dbt_fal') }}"
    freshness:
      warn_after: { "count": 5, "period": minute }
      error_after: { "count": 30, "period": minute }
    tables:
      - name: freshness_table
        loaded_at_field: "current_timestamp"
        columns:
          - name: info
            tests:
              - unique

      - name: freshness_xther # does not exist (run time error)
        loaded_at_field: "current_timestamp"
fal:
  scripts:
    - fal_scripts/freshness.py
