version: 2

# HACK: until we get write_to_model
sources:
  - name: hack_source
    database: test
    schema: dbt_fal
    tables:
      - name: orders_forecast

models:
  - name: orders_forecast
    meta:
      fal:
        scripts:
          after:
            - models/orders_forecast.py
