version: 2

sources:
  - name: results
    database: "{{ env_var('DBT_DATABASE', 'test') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'dbt_fal') }}"
    tables:
      - name: some_source
        columns:
          - name: my_text
            tests:
              - not_null
          - name: my_int
            tests:
              - not_null

models:
  - name: some_model
    columns:
      - name: my_text
        tests:
          - not_null
      - name: my_int
        tests:
          - not_null

    meta:
      fal:
        scripts:
          after:
            - fal_scripts/write_to_source_twice.py
  - name: other_model
    meta:
      fal:
        scripts:
          after:
            - fal_scripts/complete_other_model.py
