version: 2

sources:
  - name: results
    database: test
    schema: dbt_fal
    tables:
      - name: some_source

models:
  - name: some_model
    meta:
      fal:
        scripts:
          after:
            - fal_scripts/after.py
