version: '3.9'

services:
  db:
    image: postgres:12
    container_name: fal_db
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    ports:
      - 5432:5432
  trino:
    image: trinodb/trino:latest
    volumes:
      - ./catalog:/etc/trino/catalog
    ports:
      - 8080:8080
