name: "fal_test"
version: "1.0.0"
config-version: 2
profile: "fal_test"
source-paths: ["models"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
vars:
  fal-scripts-path: "scripts"
target-path: "{{ env_var('temp_dir') }}/target"
