fal_test:
  target: dev
  outputs:
    dev:
      type: redshift
      dbname: "{{ env_var('RS_DB_NAME') }}"
      host: "{{ env_var('RS_HOST') }}"
      password: "{{ env_var('RS_PASSWORD') }}"
      port: 5432
      schema: dbt_fal
      threads: 1
      user: "{{ env_var('RS_USER') }}"
