name: "simple_test"
version: "1.0.0"
config-version: 2
profile: "fal_test"

model-paths: ["models"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  +schema: custom
  # All serverless should run on S machines by default
  +fal_machine: S
  simple_test:
    base:
      +materialized: table
      +post-hook:
        # NOTE: completely ignored for Python models
        - "ALTER TABLE {{ this }} ADD COLUMN my_post_hook text"
