name: "fal_014"
version: "1.0.0"
config-version: 2
profile: "fal_test"
model-paths: ["models"]
seed-paths: ["data"]
snapshot-paths: ["snapshots"]
target-path: "{{ env_var('temp_dir') }}/target"
vars:
  fal-scripts-path: "scripts"
  fal-models-paths: ["fal_models"]

models:
  +schema: custom
