version: 2

models:
  - name: model_a
    meta:
      fal:
        pre-hook:
          - pre_hook_1.py
          - path: pre_hook_2.py
          - path: add.py
            with:
              left: 2
              right: 3

        post-hook:
          - post_hook_1.py
          - path: post_hook_2.py
          - path: sub.py
            with:
              left: 5
              right: 2
          - path: types.py
            with:
              number: 5
              text: "type"
              sequence:
                - 1
                - 2
                - 3
              mapping:
                key: value

  - name: model_b
    meta:
      fal:
        pre-hook:
          - path: local_hook.py
          - path: funny_hook.py
            environment: funny
        post-hook:
          - path: check_imports.py
            environment: not-funny
            with:
              import: pyjokes
              expected_success: false
