version: 2

sources:
  - name: results
    database: "{{ env_var('DBT_DATABASE', 'test') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'dbt_fal') }}"
    tables:
      - name: "ns__{{ env_var('DB_NAMESPACE', '') }}__ns__other_source"
        meta:
          property:
            other: 4
      - name: "ns__{{ env_var('DB_NAMESPACE', '') }}__ns__some_source"
        columns:
          - name: my_text
            tests:
              - not_null
          - name: my_int
            tests:
              - not_null

models:
  - name: some_model
    columns:
      - name: my_text
        tests:
          - not_null
      - name: my_int
        tests:
          - not_null
    meta:
      property:
        name: some_model
        other: 1
      fal:
        scripts:
          after:
            - fal_scripts/write_to_source_twice.py
        post-hook:
          - fal_scripts/execute_sql.py
          - fal_scripts/context.py
          - fal_scripts/lists.py

  - name: other_model
    meta:
      property:
        name: other_model
        other: 2
      fal:
        scripts:
          after:
            - fal_scripts/complete_model.py

  - name: third_model
    meta:
      property:
        name: third_model
        other: 3
      fal:
        scripts:
          after:
            - fal_scripts/complete_model.py
