name: "fal_test"
version: "1.0.0"
config-version: 2
profile: "fal_test"
source-paths: ["models", "fal_scripts"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "{{ env_var('temp_dir') }}/target"
vars:
  fal-scripts-path: "fal_scripts"
