config:
  send_anonymous_usage_stats: False

fal_test:
  target: staging
  outputs:
    staging:
      type: fal
      db_profile: db
    prod:
      type: fal
      db_profile: db
      host: "{{ env_var('FAL_HOST') }}"
      key_secret: "{{ env_var('FAL_KEY_SECRET') }}"
      key_id: "{{ env_var('FAL_KEY_ID') }}"
    staging_with_teleport:
      type: fal
      db_profile: db
      teleport:
        type: s3
        s3_bucket: fal-dbt-test
        s3_region: us-east-1
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
    prod_with_teleport:
      type: fal
      db_profile: db
      host: "{{ env_var('FAL_HOST') }}"
      key_secret: "{{ env_var('FAL_KEY_SECRET') }}"
      key_id: "{{ env_var('FAL_KEY_ID') }}"
      teleport:
        type: s3
        s3_bucket: fal-dbt-test
        s3_region: us-east-1
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
    db:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE') }}"
      database: "{{ env_var('SF_DATABASE') }}"
      schema: "{{ env_var('SF_SCHEMA') }}"
      threads: 4
config:
  send_anonymous_usage_stats: False
