name: "Setup local fal installation"
description: "Installs local fal installing wheel from Poetry build"

inputs:
  python:
    required: true
    description: "Python version"
  dbt:
    required: false
    default: "latest"
    description: "dbt version"
  adapter:
    required: true
    description: "dbt adapter"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python }}

    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: "1.1.4"

    - name: Fix jinja
      shell: sh
      run: pip install markupsafe==2.0.1

    - name: Install fal
      shell: sh
      run: |
        poetry build
        pip install dist/fal-0.1.0-py3-none-any.whl

    - name: Install dbt
      shell: bash
      run: |
        if [[ '${{ inputs.dbt }}' == 'latest' ]]
        then
          pip install dbt-${{ inputs.adapter }}
        elif [[ '${{ inputs.dbt }}' =~ ^1.*$ ]]
        then
          pip install dbt-${{ inputs.adapter }}==${{ inputs.dbt }}
        else
          echo "Invalid dbt version to install"
          exit 2
        fi
