name: Run Integration Tests

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - "examples/**"
      - "docsite/**"
      - "README.md"
      - "LICENSE"
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  behave:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8"]
        dbt: ["0.20", "0.21", "1.0", "latest"]

    # Run only the latest commit pushed to PR
    concurrency:
      group: "behave-${{ github.head_ref }}-${{ github.workflow }}-${{ matrix.dbt }}-${{ matrix.python }}"
      cancel-in-progress: true

    steps:
      - name: Setup local fal
        uses: fal-ai/fal/.github/actions/setup-local-fal@dry-workflow
        with:
          python: ${{ matrix.python }}
          dbt: ${{ matrix.dbt }}
          adapter: postgres

      - name: Start test Docker database
        working-directory: integration_tests
        run: docker-compose up -d

      - name: Setup behave
        run: pip install behave

      - name: Run tests
        working-directory: integration_tests
        env:
          FAL_STATS_ENABLED: false
        run: behave

  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8"]
        dbt: ["0.20", "0.21", "1.0", "latest"]

    # Run only the latest commit pushed to PR
    concurrency:
      group: "pytest-${{ github.head_ref }}-${{ github.workflow }}-${{ matrix.dbt }}-${{ matrix.python }}"
      cancel-in-progress: true

    steps:
      - name: Setup local fal
        uses: fal-ai/fal/.github/actions/setup-local-fal@dry-workflow
        with:
          python: ${{ matrix.python }}
          dbt: ${{ matrix.dbt }}
          adapter: postgres

      - name: Start test Docker database
        working-directory: tests
        run: docker-compose up -d

      - name: Setup pytest
        run: pip install pytest mock black

      - name: Run dbt
        run: |
          dbt run --profiles-dir tests/mock/mockProfile/ --project-dir tests/mock

      - name: Run tests
        env:
          FAL_STATS_ENABLED: false
        run: pytest tests -s
