name: Run Tests

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8.x"]
        dbt: ["0.20.1", "0.21.1", "1.0.0"]

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.4"

      - name: Install fal
        run: |
          poetry install

      - name: Install dbt
        run: |
          if [[ '${{ matrix.dbt }}' =~ ^0.*$ ]]
          then
            poetry run pip install dbt==${{ matrix.dbt }}
          else
            poetry run pip install dbt-bigquery==${{ matrix.dbt }}
          fi


      - name: Test
        run: poetry run pytest -s
