name: Run Integration Tests on Different Profiles

on:
  schedule:
    # every midnight
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  postgres:
    uses: fal-ai/fal/.github/workflows/integration_tests.yml@dry-workflow
    with:
      python_versions: '["3.7", "3.8", "3.9"]'
      dbt_versions: '["latest"]'
      dbt_adapter: postgres
      docker_db: true

  bigquery:
    uses: fal-ai/fal/.github/workflows/integration_tests.yml@dry-workflow
    with:
      python_versions: '["3.7", "3.8", "3.9"]'
      dbt_versions: '["latest"]'
      dbt_adapter: bigquery
    secrets:
      env_vars: >
        DBT_DATABASE="${{ secrets.GCP_PROJECT_ID }}"
        DBT_SCHEMA="${{ secrets.BQ_DATASET }}"
        KEYFILE="${{ secrets.GCP_SA_KEY }}"
        GCLOUD_PROJECT="${{ secrets.GCP_PROJECT_ID }}"
        BQ_DATASET="${{ secrets.BQ_DATASET }}"

  snowflake:
    uses: fal-ai/fal/.github/workflows/integration_tests.yml@dry-workflow
    with:
      python_versions: '["3.7", "3.8", "3.9"]'
      dbt_versions: '["latest"]'
      dbt_adapter: snowflake
    secrets:
      env_vars: >
        DBT_DATABASE="${{ secrets.SF_DATABASE }}"
        DBT_SCHEMA="${{ secrets.SF_SCHEMA }}"
        SF_ACCOUNT="${{ secrets.SF_ACCOUNT }}"
        SF_USER="${{ secrets.SF_USER }}"
        SF_PASSWORD="${{ secrets.SF_PASSWORD }}"
        SF_ROLE="${{ secrets.SF_ROLE }}"
        SF_DATABASE="${{ secrets.SF_DATABASE }}"
        SF_WAREHOUSE="${{ secrets.SF_WAREHOUSE }}"
        SF_SCHEMA="${{ secrets.SF_SCHEMA }}"

  redshift:
    uses: fal-ai/fal/.github/workflows/integration_tests.yml@dry-workflow
    with:
      python_versions: '["3.7", "3.8", "3.9"]'
      dbt_versions: '["latest"]'
      dbt_adapter: redshift
      # TODO: test against real Redshift
      docker_db: true
    secrets:
      env_vars: >
        DBT_DATABASE="${{ secrets.RS_DB_NAME }}"
        DBT_SCHEMA="dbt_fal"
        RS_DB_NAME="${{ secrets.RS_DB_NAME }}"
        RS_SCHEMA="dbt_fal"
        RS_HOST="${{ secrets.RS_HOST }}"
        RS_PASSWORD="${{ secrets.RS_PASSWORD }}"
        RS_PORT="${{ secrets.RS_PORT }}"
        RS_USER="${{ secrets.RS_USER }}"
