config:
  send_anonymous_usage_stats: False

fal_test:
  target: integration_tests
  outputs:
    integration_tests:
      type: fal
      db_profile: db
    db:
      type: trino
      user: user
      host: localhost
      port: 8080
      database: postgresql
      schema: dbt_fal
      threads: 8
      http_scheme: http
      session_properties:
        query_max_run_time: 5d
        exchange_compression: True
